/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { conversationId, visitorInfo, messages } = body;

    if (!conversationId || !visitorInfo || !messages?.length) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const { name, email, sessionId } = visitorInfo;
    const startedAt = messages[0]?.timestamp || new Date().toISOString();
    const endedAt = new Date().toISOString();
    const startMs = new Date(startedAt).getTime();
    const endMs = new Date(endedAt).getTime();
    const durationMin = Math.round((endMs - startMs) / 60000);

    const conversationText = messages
      .filter((m: any) => m.role !== "system")
      .map((m: any) => `${m.role === "user" ? name : "Assistant"}: ${m.content}`)
      .join("\n\n");

    // Generate AI summary
    let summary = "Session ended without summary.";
    try {
      const { providerFactory } = await import("@/lib/providers");
      const aiClient = providerFactory.getChatProvider();
      const summaryRes = await aiClient.generate({
        prompt: `You are a CRM assistant. Summarize this customer conversation for a business owner. Extract:
1. Visitor overview
2. Main questions asked
3. Services discussed
4. Detected intent (inquiry / hiring / booking / research)
5. Appointment status
6. Recommended follow-up actions

Visitor: ${name} (${email})
Duration: ${durationMin} minutes
Conversation:
${conversationText}

Write a concise, professional business summary.`
      });
      if (summaryRes?.content) summary = summaryRes.content;
    } catch (err: any) {
      console.error("[end-session] Summary generation failed:", err?.message);
    }

    // Update Supabase conversation
    let supabaseError = null;
    try {
      const { createClient } = await import("@supabase/supabase-js");
      const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!
      );
      const { error } = await supabase
        .from("conversations")
        .update({ status: "ended", ended_at: endedAt, summary, visitor_name: name, visitor_email: email })
        .eq("id", conversationId);
      if (error) supabaseError = error;
    } catch (err: any) {
      console.error("[end-session] Supabase update failed:", err?.message);
      supabaseError = err;
    }

    // Send email notification
    let emailSent = false;
    try {
      const { Resend } = await import("resend");
      const resend = new Resend(process.env.RESEND_API_KEY);
      const html = `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#1a1a1a;">
        <h2 style="color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:12px;">New RAGX Visitor Session — ${name}</h2>
        <h3 style="color:#475569;">Visitor Information</h3>
        <table style="width:100%">
          <tr><td style="color:#64748b;width:140px;padding:6px 0">Name</td><td style="font-weight:600">${name}</td></tr>
          <tr><td style="color:#64748b;padding:6px 0">Email</td><td>${email}</td></tr>
          <tr><td style="color:#64748b;padding:6px 0">Session ID</td><td style="font-family:monospace;font-size:12px">${sessionId || conversationId}</td></tr>
          <tr><td style="color:#64748b;padding:6px 0">Started</td><td>${new Date(startedAt).toLocaleString()}</td></tr>
          <tr><td style="color:#64748b;padding:6px 0">Ended</td><td>${new Date(endedAt).toLocaleString()}</td></tr>
          <tr><td style="color:#64748b;padding:6px 0">Duration</td><td>${durationMin} minute(s)</td></tr>
        </table>
        <h3 style="color:#475569;margin-top:24px">Conversation Summary</h3>
        <div style="background:#f8fafc;border-left:4px solid #3b82f6;padding:16px;border-radius:4px;white-space:pre-wrap;font-size:14px;line-height:1.6">${summary}</div>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0">
        <p style="color:#94a3b8;font-size:12px">Generated by RAGX — Musharraf Aziz AI Knowledge System</p>
      </div>`;
      const { error: emailError } = await resend.emails.send({
        from: process.env.RESEND_FROM_EMAIL || "ragx@maziz.me",
        to: [process.env.ADMIN_EMAIL || "io@maziz.me"],
        subject: `New RAGX Visitor Session — ${name}`,
        html,
      });
      if (!emailError) emailSent = true;
      else console.error("[end-session] Email error:", emailError);
    } catch (err: any) {
      console.error("[end-session] Email failed:", err?.message);
    }

    return NextResponse.json({
      success: true,
      summary,
      endedAt,
      emailSent,
      supabaseError: supabaseError ? String((supabaseError as any).message || supabaseError) : null,
    });
  } catch (error: any) {
    console.error("[end-session] Unhandled error:", error?.message);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
